service ssh start
#service rsyslog start
#service vsftpd start
#service nginx start
#service php7.2-fpm start
#service mysql start
#service cron start
#service postfix start
#service dovecot start
#service bind9 start
#service apache2 start
#service proftpd start
#service vsftpd start
#service pure-ftpd start
#service exim4 start
